window.VOID_CATALOG = {
  "schema": "void.catalog.v0.1",
  "generated_from": "ChatGPT project/conversation file surface",
  "generated_at": "2026-09-30T21:10:00Z",
  "origin_anchor": "NEXUS://0.0.0",
  "particle_count": 68,
  "policy": {
    "originals": "Preserved outside Git and never overwritten by normalized or enhanced derivatives.",
    "github": "Stores code-formatted working copies, normalized derivatives, manifests, schemas and release-ready stars.",
    "binaries": "Manifest-only until explicitly converted, Git-LFS-managed, or attached as a release asset.",
    "hashes": "Exact SHA-256 is mandatory before VERIFIED promotion."
  },
  "particles": [
    {
      "particle_id": "void://particle/74865575",
      "source_ref": "file_00000000674881f9ae8cbd657082df9a",
      "name": "gaia-nexus-godsgift (3).html",
      "slug": "gaia-nexus-godsgift-(3).html",
      "mime_type": "text/html",
      "size_bytes": 368879,
      "source_kind": "imported",
      "source_turn": 1,
      "created_at": "2026-09-30T09:29:31.100731+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 1954960757,
        "ring": 0,
        "theta": 0,
        "radius": 18,
        "z": -4
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/c24cbde3",
      "source_ref": "file_000000007a8481f9a406a6c781e132bd",
      "name": "godswatch_x5f_parsect_x5f_tracker.html",
      "slug": "godswatch_x5f_parsect_x5f_tracker.html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "imported",
      "source_turn": 1,
      "created_at": "2026-09-30T09:29:31.100731+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 3259809251,
        "ring": 0,
        "theta": 3.88322208,
        "radius": 18,
        "z": -3
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/216ef429",
      "source_ref": "file_0000000042f081f9aca27dcbe1b207ec",
      "name": "bibliotheque_x5f_v34_x5f_registry.json.txt",
      "slug": "bibliotheque_x5f_v34_x5f_registry.json.txt",
      "mime_type": "text/plain",
      "size_bytes": null,
      "source_kind": "imported",
      "source_turn": 1,
      "created_at": "2026-09-30T09:29:31.100731+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 560919593,
        "ring": 0,
        "theta": 1.48325885,
        "radius": 18,
        "z": -2
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/0c2b1e39",
      "source_ref": "file_00000000ce6481f98200250026634cfc",
      "name": "MASTER_AUTHORITY_ISE_BYPASS.docx",
      "slug": "MASTER_AUTHORITY_ISE_BYPASS.docx",
      "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "size_bytes": null,
      "source_kind": "imported",
      "source_turn": 1,
      "created_at": "2026-09-30T09:29:31.100731+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "document-orb",
      "orb": {
        "seed_u32": 204152377,
        "ring": 0,
        "theta": 5.36648093,
        "radius": 18,
        "z": -1
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/81c1dcd1",
      "source_ref": "file_0000000070d481f9b20961e9dc40138f",
      "name": "bibliotheque_x5f_v34_x5f_full_x5f_hashes_x5f_evidence (1).xlsx",
      "slug": "bibliotheque_x5f_v34_x5f_full_x5f_hashes_x5f_evidence-(1).xlsx",
      "mime_type": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
      "size_bytes": null,
      "source_kind": "imported",
      "source_turn": 1,
      "created_at": "2026-09-30T09:29:31.100731+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "document-orb",
      "orb": {
        "seed_u32": 2176965841,
        "ring": 0,
        "theta": 2.9665177,
        "radius": 18,
        "z": 0
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/7130e1cf",
      "source_ref": "file_000000005fd481f99f0efa3c6e9b2816",
      "name": "GoldenArmy_x5f_Continuous_x5f_Engine.py(3).txt",
      "slug": "GoldenArmy_x5f_Continuous_x5f_Engine.py(3).txt",
      "mime_type": "text/plain",
      "size_bytes": null,
      "source_kind": "imported",
      "source_turn": 1,
      "created_at": "2026-09-30T09:29:31.100731+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 1899028943,
        "ring": 0,
        "theta": 0.56655447,
        "radius": 18,
        "z": 1
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/1bf025af",
      "source_ref": "file_00000000d25481f9b65a065a2fbb54e8",
      "name": "ADAM_CANONICAL_DOCUMENTATION_v1.0.md",
      "slug": "ADAM_CANONICAL_DOCUMENTATION_v1.0.md",
      "mime_type": "application/octet-stream",
      "size_bytes": null,
      "source_kind": "generated",
      "source_turn": 1,
      "created_at": "2026-09-30T09:36:12.792143+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 468723119,
        "ring": 0,
        "theta": 4.44977654,
        "radius": 18,
        "z": 2
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/b2b3c4f3",
      "source_ref": "file_00000000e99481f999a1e7fc8c4bc304",
      "name": "adam_event.schema.v1.json",
      "slug": "adam_event.schema.v1.json",
      "mime_type": "application/octet-stream",
      "size_bytes": null,
      "source_kind": "generated",
      "source_turn": 1,
      "created_at": "2026-09-30T09:36:29.684520+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 2998125811,
        "ring": 0,
        "theta": 2.04981331,
        "radius": 18,
        "z": 3
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/e11c42c1",
      "source_ref": "file_00000000292c81f9a177090195bec547",
      "name": "GOD_ADAM_Organization_Blueprint_Roadmap_v1.0.docx",
      "slug": "GOD_ADAM_Organization_Blueprint_Roadmap_v1.0.docx",
      "mime_type": "application/octet-stream",
      "size_bytes": null,
      "source_kind": "generated",
      "source_turn": 3,
      "created_at": "2026-09-30T12:33:07.187103+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "binary-orb",
      "orb": {
        "seed_u32": 3776725697,
        "ring": 0,
        "theta": 5.93303539,
        "radius": 18,
        "z": 4
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/280fab6c",
      "source_ref": "file_00000000c2fc81f9a1fba046c8f677d9",
      "name": "GOD_ADAM_Organization_Blueprint_Roadmap_v1.0.pdf",
      "slug": "GOD_ADAM_Organization_Blueprint_Roadmap_v1.0.pdf",
      "mime_type": "application/octet-stream",
      "size_bytes": null,
      "source_kind": "generated",
      "source_turn": 3,
      "created_at": "2026-09-30T12:33:22.379853+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "binary-orb",
      "orb": {
        "seed_u32": 672115564,
        "ring": 0,
        "theta": 3.53307216,
        "radius": 18,
        "z": -4
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/633ba655",
      "source_ref": "file_000000007c9c81f9934a24fa2632b5e2",
      "name": "GOD_ADAM_Network_IP_Plan_v1.0.xlsx",
      "slug": "GOD_ADAM_Network_IP_Plan_v1.0.xlsx",
      "mime_type": "application/octet-stream",
      "size_bytes": null,
      "source_kind": "generated",
      "source_turn": 3,
      "created_at": "2026-09-30T12:36:42.559165+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "binary-orb",
      "orb": {
        "seed_u32": 1664853589,
        "ring": 0,
        "theta": 1.13310893,
        "radius": 18,
        "z": -3
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/eac89e11",
      "source_ref": "file_00000000e44c81f98ebb6ecddee771c3",
      "name": "GOD_ADAM_Organization_Blueprint_Roadmap_v1.0.docx",
      "slug": "GOD_ADAM_Organization_Blueprint_Roadmap_v1.0.docx",
      "mime_type": "application/octet-stream",
      "size_bytes": null,
      "source_kind": "generated",
      "source_turn": 3,
      "created_at": "2026-09-30T12:37:18.916858+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "binary-orb",
      "orb": {
        "seed_u32": 3939016209,
        "ring": 0,
        "theta": 5.01633101,
        "radius": 18,
        "z": -2
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/fed92656",
      "source_ref": "file_000000001fd081f9b5d8bc4ba559e3ce",
      "name": "GOD_ADAM_Organization_Blueprint_Roadmap_v1.0.pdf",
      "slug": "GOD_ADAM_Organization_Blueprint_Roadmap_v1.0.pdf",
      "mime_type": "application/octet-stream",
      "size_bytes": null,
      "source_kind": "generated",
      "source_turn": 3,
      "created_at": "2026-09-30T12:37:18.916858+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "binary-orb",
      "orb": {
        "seed_u32": 4275643990,
        "ring": 0,
        "theta": 2.61636778,
        "radius": 18,
        "z": -1
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/9d4fd9eb",
      "source_ref": "file_000000007a1881f9b0ea46eb0193e0a8",
      "name": "GOD_ADAM_Network_IP_Plan_v1.0.xlsx",
      "slug": "GOD_ADAM_Network_IP_Plan_v1.0.xlsx",
      "mime_type": "application/octet-stream",
      "size_bytes": null,
      "source_kind": "generated",
      "source_turn": 3,
      "created_at": "2026-09-30T12:37:18.916858+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "binary-orb",
      "orb": {
        "seed_u32": 2639256043,
        "ring": 0,
        "theta": 0.21640455,
        "radius": 18,
        "z": 0
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/105a3797",
      "source_ref": "file_00000000d39481f9b3c6b497f77889d5",
      "name": "Android Control and Sandbox Bypass Research",
      "slug": "Android-Control-and-Sandbox-Bypass-Research",
      "mime_type": "application/pdf",
      "size_bytes": 202220,
      "source_kind": "imported",
      "source_turn": 4,
      "created_at": "2026-09-30T15:14:58.928137+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "document-orb",
      "orb": {
        "seed_u32": 274347927,
        "ring": 0,
        "theta": 4.09962663,
        "radius": 18,
        "z": 1
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/7965ffc8",
      "source_ref": "file_000000000ac4820c9733baef5b908cc1",
      "name": "Architectural Use Case Analysis",
      "slug": "Architectural-Use-Case-Analysis",
      "mime_type": "application/pdf",
      "size_bytes": 67595,
      "source_kind": "imported",
      "source_turn": 4,
      "created_at": "2026-09-30T15:14:58.928137+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "document-orb",
      "orb": {
        "seed_u32": 2036727752,
        "ring": 0,
        "theta": 1.6996634,
        "radius": 18,
        "z": 2
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/c9558544",
      "source_ref": "file_000000004be481f9a2f77f5acde3024d",
      "name": "AudioHub- Overclocking Temperature Manifold & Multimodal Duplex Hub.pdf",
      "slug": "AudioHub-Overclocking-Temperature-Manifold-Multimodal-Duplex-Hub.pdf",
      "mime_type": "application/pdf",
      "size_bytes": 193262,
      "source_kind": "imported",
      "source_turn": 4,
      "created_at": "2026-09-30T15:14:58.928137+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "document-orb",
      "orb": {
        "seed_u32": 3377825092,
        "ring": 0,
        "theta": 5.58288547,
        "radius": 18,
        "z": 3
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/61843aca",
      "source_ref": "file_00000000314081f49de2a6cdaedeb073",
      "name": "audio_x5f_maximum_x5f_efficiency_x5f_usage.html",
      "slug": "audio_x5f_maximum_x5f_efficiency_x5f_usage.html",
      "mime_type": "text/html",
      "size_bytes": 193558,
      "source_kind": "imported",
      "source_turn": 4,
      "created_at": "2026-09-30T15:14:58.928137+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 1636055754,
        "ring": 0,
        "theta": 3.18292224,
        "radius": 18,
        "z": 4
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/1d87c272",
      "source_ref": "file_0000000060c481f5b099cc3c1a91e060",
      "name": "aurora_x5f_singularity_x5f_stack_x5f_all.html",
      "slug": "aurora_x5f_singularity_x5f_stack_x5f_all.html",
      "mime_type": "text/html",
      "size_bytes": 193745,
      "source_kind": "imported",
      "source_turn": 4,
      "created_at": "2026-09-30T15:14:58.928137+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 495436402,
        "ring": 1,
        "theta": 0.78295902,
        "radius": 25,
        "z": -4
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/638355e8",
      "source_ref": "file_0000000064a481f9b3cd967f91eb8d93",
      "name": "azazels_ledger_dataframe_ai.html",
      "slug": "azazels_ledger_dataframe_ai.html",
      "mime_type": "text/html",
      "size_bytes": 9332,
      "source_kind": "imported",
      "source_turn": 4,
      "created_at": "2026-09-30T15:14:58.928137+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 1669551592,
        "ring": 1,
        "theta": 4.66618109,
        "radius": 25,
        "z": -3
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/9bedee6d",
      "source_ref": "file_00000000f05881f59b54fccbc821135c",
      "name": "the asynchronous serialization adapter..docx",
      "slug": "the-asynchronous-serialization-adapter..docx",
      "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "size_bytes": null,
      "source_kind": "imported",
      "source_turn": 4,
      "created_at": "2026-09-30T15:14:58.928137+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "document-orb",
      "orb": {
        "seed_u32": 2616061549,
        "ring": 1,
        "theta": 2.26621786,
        "radius": 25,
        "z": -2
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/2dab78c6",
      "source_ref": "file_00000000b8e0820ca0a1aa0ae09fe7bf",
      "name": "both the lockstep data integrity verification suite. we can perform the verification procedure. by having the secondary system. take the expected output and reverse engineer the pathways in which the current trajectory pair is heading. taking alternative routes back to the command first character command line. essentially providing a dual parrallel path of code completion.docx",
      "slug": "both-the-lockstep-data-integrity-verification-suite.-we-can-perform-the-verification-procedure.-by-having-the-secondary-system.-take-the-exp",
      "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "size_bytes": null,
      "source_kind": "imported",
      "source_turn": 4,
      "created_at": "2026-09-30T15:14:58.928137+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "document-orb",
      "orb": {
        "seed_u32": 766212294,
        "ring": 1,
        "theta": 6.14943994,
        "radius": 25,
        "z": -1
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/6604172e",
      "source_ref": "file_00000000911881f984ab79ccf6b6ef0d",
      "name": "Cross-Tab Manifold Load Matrix.docx",
      "slug": "Cross-Tab-Manifold-Load-Matrix.docx",
      "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "size_bytes": null,
      "source_kind": "imported",
      "source_turn": 4,
      "created_at": "2026-09-30T15:14:58.928137+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "document-orb",
      "orb": {
        "seed_u32": 1711544110,
        "ring": 1,
        "theta": 3.74947671,
        "radius": 25,
        "z": 0
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/8b36d216",
      "source_ref": "file_00000000734081f9bfb4ba2339e1090f",
      "name": "workspacemanagementdashboard.html",
      "slug": "workspacemanagementdashboard.html",
      "mime_type": "text/html",
      "size_bytes": 47723,
      "source_kind": "imported",
      "source_turn": 6,
      "created_at": "2026-09-30T21:17:20.229000+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 2335625750,
        "ring": 1,
        "theta": 1.34951348,
        "radius": 25,
        "z": 1
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/870d8a4d",
      "source_ref": "file_00000000df4481f5b7c0626f2e4a475e",
      "name": "const express   require  express.txt",
      "slug": "const-express-require-express.txt",
      "mime_type": "text/plain",
      "size_bytes": 67219,
      "source_kind": "imported",
      "source_turn": 6,
      "created_at": "2026-09-30T21:17:20.229000+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 2265811533,
        "ring": 1,
        "theta": 5.23273556,
        "radius": 25,
        "z": 2
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/e0f5de5f",
      "source_ref": "file_00000000869881f981c71659d9548e81",
      "name": "DeepResearchStudio.html",
      "slug": "DeepResearchStudio.html",
      "mime_type": "text/html",
      "size_bytes": 19097,
      "source_kind": "imported",
      "source_turn": 6,
      "created_at": "2026-09-30T21:17:20.229000+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 3774209631,
        "ring": 1,
        "theta": 2.83277233,
        "radius": 25,
        "z": 3
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/ee7a4bc5",
      "source_ref": "file_00000000bb6881f9be06f7d60d62b4d3",
      "name": "Sovereign Notebook.html",
      "slug": "Sovereign-Notebook.html",
      "mime_type": "text/html",
      "size_bytes": 18961,
      "source_kind": "imported",
      "source_turn": 6,
      "created_at": "2026-09-30T21:17:20.229000+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 4000992197,
        "ring": 1,
        "theta": 0.4328091,
        "radius": 25,
        "z": 4
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/eaff1be6",
      "source_ref": "file_000000005c54820ca32a8f5abceac8c7",
      "name": "The ChimeraSphynx.html",
      "slug": "The-ChimeraSphynx.html",
      "mime_type": "text/html",
      "size_bytes": 11857,
      "source_kind": "imported",
      "source_turn": 6,
      "created_at": "2026-09-30T21:17:20.229000+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 3942587366,
        "ring": 1,
        "theta": 4.31603118,
        "radius": 25,
        "z": -4
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/342d22ac",
      "source_ref": "file_0000000026d881f5a62d48c680b440d3",
      "name": "GAIA_AIPDF_Vault_Bundle_v2 (1).zip",
      "slug": "GAIA_AIPDF_Vault_Bundle_v2-(1).zip",
      "mime_type": "application/zip",
      "size_bytes": 6813459,
      "source_kind": "imported",
      "source_turn": 6,
      "created_at": "2026-09-30T21:17:20.229000+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "archive-nebula",
      "orb": {
        "seed_u32": 875373228,
        "ring": 1,
        "theta": 1.91606795,
        "radius": 25,
        "z": -3
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/c95f8571",
      "source_ref": "file_00000000b52c81f9ad65df77620ee7e8",
      "name": "devtools_mudkip_snip_curcumference_noodling_cast_fishing_sign.md",
      "slug": "devtools_mudkip_snip_curcumference_noodling_cast_fishing_sign.md",
      "mime_type": "text/markdown",
      "size_bytes": 1930,
      "source_kind": "imported",
      "source_turn": 6,
      "created_at": "2026-09-30T21:17:20.229000+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 3378480497,
        "ring": 1,
        "theta": 5.79929002,
        "radius": 25,
        "z": -2
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/de8f533a",
      "source_ref": "file_00000000498081f9a84596ece64762c2",
      "name": "daHornet",
      "slug": "daHornet",
      "mime_type": "application/octet-stream",
      "size_bytes": 3834231,
      "source_kind": "imported",
      "source_turn": 6,
      "created_at": "2026-09-30T21:17:20.229000+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "binary-orb",
      "orb": {
        "seed_u32": 3733934906,
        "ring": 1,
        "theta": 3.39932679,
        "radius": 25,
        "z": -1
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/558a33cc",
      "source_ref": "file_000000003b2081f9997061454a76f62c",
      "name": "azazel-sovereign.zip",
      "slug": "azazel-sovereign.zip",
      "mime_type": "application/zip",
      "size_bytes": 1594746,
      "source_kind": "imported",
      "source_turn": 6,
      "created_at": "2026-09-30T21:17:20.229000+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "archive-nebula",
      "orb": {
        "seed_u32": 1435120588,
        "ring": 1,
        "theta": 0.99936356,
        "radius": 25,
        "z": 0
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/0b0a3f34",
      "source_ref": "file_00000000154481f9839222029a4d821b",
      "name": "GeminiNexus_ An Analysis of Core Technologies and a Blueprint for Project Documentation.docx",
      "slug": "GeminiNexus_-An-Analysis-of-Core-Technologies-and-a-Blueprint-for-Project-Documentation.docx",
      "mime_type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
      "size_bytes": 3041374,
      "source_kind": "imported",
      "source_turn": 6,
      "created_at": "2026-09-30T21:17:20.229000+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "document-orb",
      "orb": {
        "seed_u32": 185220916,
        "ring": 1,
        "theta": 4.88258564,
        "radius": 25,
        "z": 1
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/390afbbf",
      "source_ref": "file_00000000b93c81f794372db242b4b9b8",
      "name": "Locate Memory Fabric.txt",
      "slug": "Locate-Memory-Fabric.txt",
      "mime_type": "text/plain",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 957021119,
        "ring": 1,
        "theta": 2.48262241,
        "radius": 25,
        "z": 2
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/6836779e",
      "source_ref": "file_00000000ba5881fd886b25a2c81eb71b",
      "name": "Create Integration Roadmap.txt",
      "slug": "Create-Integration-Roadmap.txt",
      "mime_type": "text/plain",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 1748400030,
        "ring": 1,
        "theta": 0.08265918,
        "radius": 25,
        "z": 3
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/f43f4ada",
      "source_ref": "file_0000000013d081fd854217a83021f517",
      "name": "Create Integration Roadmap.txt",
      "slug": "Create-Integration-Roadmap.txt",
      "mime_type": "text/plain",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 4097788634,
        "ring": 1,
        "theta": 3.96588126,
        "radius": 25,
        "z": 4
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/ebc41627",
      "source_ref": "file_0000000013c082308dac639d291740a1",
      "name": "ALLAH-Nexus-Enclave-Protocol-2.0-CLEAN-1.md",
      "slug": "ALLAH-Nexus-Enclave-Protocol-2.0-CLEAN-1.md",
      "mime_type": "text/markdown",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 3955496487,
        "ring": 2,
        "theta": 1.56591803,
        "radius": 32,
        "z": -4
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/e061ca2d",
      "source_ref": "file_00000000e7e482309b0b44bec02666ce",
      "name": "Memory Fabric Kronosphere (2).html",
      "slug": "Memory-Fabric-Kronosphere-(2).html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 3764505133,
        "ring": 2,
        "theta": 5.44914011,
        "radius": 32,
        "z": -3
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/ffc51f04",
      "source_ref": "file_000000008a848211b9e19bc9649561b6",
      "name": "Project Chimera_ The Genesis Logs.html",
      "slug": "Project-Chimera_-The-Genesis-Logs.html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 4291108612,
        "ring": 2,
        "theta": 3.04917688,
        "radius": 32,
        "z": -2
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/3730e7c0",
      "source_ref": "file_00000000f3d08211815c9256a50adb66",
      "name": "Project Chimera_ Nexus Core Interface (Osmosis Protocol Active).html",
      "slug": "Project-Chimera_-Nexus-Core-Interface-(Osmosis-Protocol-Active).html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 925951936,
        "ring": 2,
        "theta": 0.64921365,
        "radius": 32,
        "z": -1
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/2cd20507",
      "source_ref": "file_00000000534081fd898b35deb03fb32e",
      "name": "Android Wallpaper Configuration.txt",
      "slug": "Android-Wallpaper-Configuration.txt",
      "mime_type": "text/plain",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 751961351,
        "ring": 2,
        "theta": 4.53243573,
        "radius": 32,
        "z": 0
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/380b326a",
      "source_ref": "file_000000004dcc81f690e63f4a6b3a23b4",
      "name": "nexus_x5f_gaia_x5f_existential_x5f_core.html",
      "slug": "nexus_x5f_gaia_x5f_existential_x5f_core.html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 940257898,
        "ring": 2,
        "theta": 2.1324725,
        "radius": 32,
        "z": 1
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/a91362a3",
      "source_ref": "file_000000004a0c81f6b8110010fa77e482",
      "name": "Termux geminicli setup.txt",
      "slug": "Termux-geminicli-setup.txt",
      "mime_type": "text/plain",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 2836619939,
        "ring": 2,
        "theta": 6.01569457,
        "radius": 32,
        "z": 2
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/11ceae1c",
      "source_ref": "file_000000001eb881f6981d19e745e497c4",
      "name": "Optimize Finances With Stripe GitHub.txt",
      "slug": "Optimize-Finances-With-Stripe-GitHub.txt",
      "mime_type": "text/plain",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 298757660,
        "ring": 2,
        "theta": 3.61573134,
        "radius": 32,
        "z": 3
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/3f457c65",
      "source_ref": "file_00000000846081f5947403594670019a",
      "name": "GAIA News Vector.txt",
      "slug": "GAIA-News-Vector.txt",
      "mime_type": "text/plain",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 1061518437,
        "ring": 2,
        "theta": 1.21576811,
        "radius": 32,
        "z": 4
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/56d638c6",
      "source_ref": "file_00000000ceb4820c832bf53d3c0f15dc",
      "name": "Public Sharing Discovery.txt",
      "slug": "Public-Sharing-Discovery.txt",
      "mime_type": "text/plain",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 1456879814,
        "ring": 2,
        "theta": 5.09899019,
        "radius": 32,
        "z": -4
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/8a9ff5bc",
      "source_ref": "file_00000000388481f9acdb5a55ffdb2b81",
      "name": "TDoc 9208 Evolution.txt",
      "slug": "TDoc-9208-Evolution.txt",
      "mime_type": "text/plain",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 2325738940,
        "ring": 2,
        "theta": 2.69902696,
        "radius": 32,
        "z": -3
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/371aebc9",
      "source_ref": "file_00000000403881f984e01741bd4a22a6",
      "name": "⚛️ Cosmic Guardian — Polyglot Embed Field_copy.PDF.pdf",
      "slug": "Cosmic-Guardian-Polyglot-Embed-Field_copy.PDF.pdf",
      "mime_type": "application/pdf",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "document-orb",
      "orb": {
        "seed_u32": 924511177,
        "ring": 2,
        "theta": 0.29906373,
        "radius": 32,
        "z": -2
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/76341b00",
      "source_ref": "file_000000008d6081f9a0dfa2438322b2f6",
      "name": "omni_dimensional_convergence_engine (2).html",
      "slug": "omni_dimensional_convergence_engine-(2).html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 1983126272,
        "ring": 2,
        "theta": 4.18228581,
        "radius": 32,
        "z": -1
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/1649d684",
      "source_ref": "file_00000000ac0081f99db904b732bdae22",
      "name": "Yahweh-Hamiltonian-Carousel-Os (EYEPupil).html",
      "slug": "Yahweh-Hamiltonian-Carousel-Os-(EYEPupil).html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 373937796,
        "ring": 2,
        "theta": 1.78232258,
        "radius": 32,
        "z": 0
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/c358db1a",
      "source_ref": "file_000000009e0881f99a20d7e25b34e044",
      "name": "Yahweh-Hamiltonian-Carousel-Os (2eyes).html",
      "slug": "Yahweh-Hamiltonian-Carousel-Os-(2eyes).html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 3277380378,
        "ring": 2,
        "theta": 5.66554466,
        "radius": 32,
        "z": 1
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/301c98f3",
      "source_ref": "file_0000000057a881f98f1edab229105ca0",
      "name": "Yahweh-Hamiltonian-Carousel-Os (1).html",
      "slug": "Yahweh-Hamiltonian-Carousel-Os-(1).html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 807180531,
        "ring": 2,
        "theta": 3.26558143,
        "radius": 32,
        "z": 2
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/1381a92e",
      "source_ref": "file_000000007f3481f9b630730af920fe74",
      "name": "Gaia-Accordion-Wallpaper.html",
      "slug": "Gaia-Accordion-Wallpaper.html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 327264558,
        "ring": 2,
        "theta": 0.8656182,
        "radius": 32,
        "z": 3
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/4976fb85",
      "source_ref": "file_0000000081e481f9ab0ebad54e7c09cb",
      "name": "Yahweh-Hamiltonian-Carousel-Os.html",
      "slug": "Yahweh-Hamiltonian-Carousel-Os.html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 1232534405,
        "ring": 2,
        "theta": 4.74884028,
        "radius": 32,
        "z": 4
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/3a82c4ec",
      "source_ref": "file_00000000b96c81f9a5625f0cf8238757",
      "name": "Hamiltonian-Singularity-Clock.html",
      "slug": "Hamiltonian-Singularity-Clock.html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 981648620,
        "ring": 3,
        "theta": 2.34887705,
        "radius": 39,
        "z": -4
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/374a8c01",
      "source_ref": "file_00000000a40c81f987bc0a251b8e6102",
      "name": "omni-ide-singularity-quine.zip",
      "slug": "omni-ide-singularity-quine.zip",
      "mime_type": "application/zip",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "archive-nebula",
      "orb": {
        "seed_u32": 927632385,
        "ring": 3,
        "theta": 6.23209912,
        "radius": 39,
        "z": -3
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/68197534",
      "source_ref": "file_00000000b81481f9b72a8bcb7eaabe83",
      "name": "Copy of Multi-Account Forensic Audit & IP Verification Specification",
      "slug": "Copy-of-Multi-Account-Forensic-Audit-IP-Verification-Specification",
      "mime_type": "application/pdf",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "document-orb",
      "orb": {
        "seed_u32": 1746498868,
        "ring": 3,
        "theta": 3.83213589,
        "radius": 39,
        "z": -2
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/419867e8",
      "source_ref": "file_0000000081c081f9bc81db3067180c84",
      "name": "Copy of Gaia Nexus LLM Guidance\n",
      "slug": "Copy-of-Gaia-Nexus-LLM-Guidance",
      "mime_type": "application/pdf",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "normalization-pending",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "document-orb",
      "orb": {
        "seed_u32": 1100507112,
        "ring": 3,
        "theta": 1.43217266,
        "radius": 39,
        "z": -1
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/1f9dd66d",
      "source_ref": "file_00000000cedc81f999f21a5158d96d45",
      "name": "Nexus-Gaia-Dynamic-Evolving-Runtime.html",
      "slug": "Nexus-Gaia-Dynamic-Evolving-Runtime.html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 530437741,
        "ring": 3,
        "theta": 5.31539474,
        "radius": 39,
        "z": 0
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/4f383c3a",
      "source_ref": "file_00000000025c81f9825d699dd449682e",
      "name": "Nexus-Spine-True-Api-Calls-Fixed.html",
      "slug": "Nexus-Spine-True-Api-Calls-Fixed.html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 1329085498,
        "ring": 3,
        "theta": 2.91543151,
        "radius": 39,
        "z": 1
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/f77fa4fb",
      "source_ref": "file_000000005c5081f9bfc48a8d8037418d",
      "name": "omni_nexus_prime_quantum_void_llm_uplink.html",
      "slug": "omni_nexus_prime_quantum_void_llm_uplink.html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 4152337659,
        "ring": 3,
        "theta": 0.51546828,
        "radius": 39,
        "z": 2
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/e8f3ee0d",
      "source_ref": "file_0000000033b081f9b848790c2c9c235b",
      "name": "QuantumVoidEngine Enhanced runtiemgemini-code-1788305040737.html",
      "slug": "QuantumVoidEngine-Enhanced-runtiemgemini-code-1788305040737.html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 3908300301,
        "ring": 3,
        "theta": 4.39869036,
        "radius": 39,
        "z": 3
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/8e6fb0b0",
      "source_ref": "file_00000000c10881f9adf873c12b8c7a77",
      "name": "Server.js",
      "slug": "Server.js",
      "mime_type": "text/javascript",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "code-star",
      "orb": {
        "seed_u32": 2389684400,
        "ring": 3,
        "theta": 1.99872713,
        "radius": 39,
        "z": 4
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/19a0c0ba",
      "source_ref": "file_000000006a8481f9a89d4e7801ecb7f4",
      "name": "sovereign_nexus_overclockit.html",
      "slug": "sovereign_nexus_overclockit.html",
      "mime_type": "text/html",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "html-star",
      "orb": {
        "seed_u32": 429965498,
        "ring": 3,
        "theta": 5.88194921,
        "radius": 39,
        "z": -4
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/0571abb1",
      "source_ref": "file_00000000566881f9b7faab6f63dea4f8",
      "name": "three.min_o18D.js",
      "slug": "three.min_o18D.js",
      "mime_type": "text/javascript",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "code-star",
      "orb": {
        "seed_u32": 91335601,
        "ring": 3,
        "theta": 3.48198598,
        "radius": 39,
        "z": -3
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/001cdf8c",
      "source_ref": "file_00000000d52c81f9883b6e5250ce1f81",
      "name": "Weaviate-Transform.js",
      "slug": "Weaviate-Transform.js",
      "mime_type": "text/javascript",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "code-star",
      "orb": {
        "seed_u32": 1892236,
        "ring": 3,
        "theta": 1.08202275,
        "radius": 39,
        "z": -2
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/ed837e94",
      "source_ref": "file_00000000319081f99cbe4e21ba214454",
      "name": "Architecture Gap Analysis.txt",
      "slug": "Architecture-Gap-Analysis.txt",
      "mime_type": "text/plain",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 3984817812,
        "ring": 3,
        "theta": 4.96524482,
        "radius": 39,
        "z": -1
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    },
    {
      "particle_id": "void://particle/5486edb8",
      "source_ref": "file_000000007c5081f98f472dbc231ba7e0",
      "name": "Drive Registry Update.txt",
      "slug": "Drive-Registry-Update.txt",
      "mime_type": "text/plain",
      "size_bytes": null,
      "source_kind": "project",
      "source_turn": 0,
      "created_at": "2026-09-30T21:17:22.870420+00:00",
      "modified_at": null,
      "origin_anchor": "NEXUS://0.0.0",
      "visibility": "private",
      "original_policy": "original-retained-outside-git",
      "code_state": "working-copy-eligible",
      "content_sha256": null,
      "quine_state": "manifest-encoded",
      "runtime_class": "text-star",
      "orb": {
        "seed_u32": 1418128824,
        "ring": 3,
        "theta": 2.56528159,
        "radius": 39,
        "z": 0
      },
      "lineage": {
        "parent_particle_ids": [],
        "derived_particle_ids": [],
        "chronology_state": "timestamp-pending-verification"
      }
    }
  ]
};
